AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: C3D - 3D File Conversion Service

Globals:
  Function:
    Architectures:
      - x86_64
    Environment:
      Variables:
        UPLOADS_BUCKET: !Ref UploadsBucket
        CONVERSIONS_BUCKET: !Ref ConversionsBucket
  Api:
    Cors:
      AllowMethods: "'GET,POST,OPTIONS'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
      AllowOrigin: "'*'"

Resources:
  UploadsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      IntelligentTieringConfigurations:
        - Id: EntireBucket
          Status: Enabled
          Tierings:
            - AccessTier: ARCHIVE_ACCESS
              Days: 90
            - AccessTier: DEEP_ARCHIVE_ACCESS
              Days: 180
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldUploads
            Status: Enabled
            ExpirationInDays: 7
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins: 
              - !Sub 'https://${CloudFrontDistribution.DomainName}'
              - 'https://the3dconverter.com'
              - 'https://www.the3dconverter.com'
              - 'http://localhost:5173'
            AllowedMethods: [GET, PUT, POST, DELETE, HEAD]
            AllowedHeaders: ['*']
            ExposedHeaders: [ETag]
  
  ConversionsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      IntelligentTieringConfigurations:
        - Id: EntireBucket
          Status: Enabled
          Tierings:
            - AccessTier: ARCHIVE_ACCESS
              Days: 90
            - AccessTier: DEEP_ARCHIVE_ACCESS
              Days: 180
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldConversions
            Status: Enabled
            ExpirationInDays: 7
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins: 
              - !Sub 'https://${CloudFrontDistribution.DomainName}'
              - 'https://the3dconverter.com'
              - 'https://www.the3dconverter.com'
              - 'http://localhost:5173'
            AllowedMethods: [GET, PUT, POST, DELETE, HEAD]
            AllowedHeaders: ['*']
            ExposedHeaders: [ETag]

  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: !Sub ${FrontendBucket.Arn}/*
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistribution}

  CloudFrontOriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub ${AWS::StackName}-OAC
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: index.html
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt FrontendBucket.RegionalDomainName
            OriginAccessControlId: !Ref CloudFrontOriginAccessControl
            S3OriginConfig:
              OriginAccessIdentity: ''
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
        CustomErrorResponses:
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html

  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.12
      Handler: app.handler
      CodeUri: backend/api/
      Timeout: 300
      MemorySize: 1024
      Policies:
        - Statement:
          - Effect: Allow
            Action:
              - s3:PutObject
              - s3:GetObject
              - s3:ListBucket
            Resource:
              - !Sub ${UploadsBucket.Arn}
              - !Sub ${UploadsBucket.Arn}/*
              - !Sub ${ConversionsBucket.Arn}
              - !Sub ${ConversionsBucket.Arn}/*
      Events:
        UploadUrl:
          Type: Api
          Properties:
            Path: /upload-url
            Method: post
        Convert:
          Type: Api
          Properties:
            Path: /convert
            Method: post
        Status:
          Type: Api
          Properties:
            Path: /status/{job_id}
            Method: get
        DownloadUrl:
          Type: Api
          Properties:
            Path: /download-url/{job_id}
            Method: get

  ConversionFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: 3D file conversion Lambda function v2
      PackageType: Image
      Timeout: 900
      MemorySize: 1024
      EphemeralStorage:
        Size: 10240
      ImageConfig:
        Command:
          - converter.handler
      Policies:
        - Statement:
          - Effect: Allow
            Action:
              - s3:GetObject
              - s3:ListBucket
            Resource:
              - !Sub ${UploadsBucket.Arn}
              - !Sub ${UploadsBucket.Arn}/*
          - Effect: Allow
            Action:
              - s3:PutObject
              - s3:GetObject
            Resource:
              - !Sub ${ConversionsBucket.Arn}
              - !Sub ${ConversionsBucket.Arn}/*
    Metadata:
      DockerTag: python3.12-v1
      DockerContext: ./backend/c3d
      Dockerfile: Dockerfile

  S3InvokeLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt ConversionFunction.Arn
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/
  CloudFrontUrl:
    Description: CloudFront distribution URL
    Value: !GetAtt CloudFrontDistribution.DomainName
  FrontendBucket:
    Description: S3 bucket for frontend hosting
    Value: !Ref FrontendBucket
  UploadsBucket:
    Description: S3 bucket for file uploads
    Value: !Ref UploadsBucket
  ConversionsBucket:
    Description: S3 bucket for converted files
    Value: !Ref ConversionsBucket
